WebApplication1/Controllers/PickFlowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
namespace WebApplication1.Controllers
{
    public class PickFlowController : Controller
    {

        NH.NHibernateOperation operation = new NH.NHibernateOperation();
        public static User user;
        Flow flow = new Flow();
        FlowDefinition flowdef = new FlowDefinition();
        public ActionResult Index()
        {
            flowdefmodellist model = new flowdefmodellist();
            model.id_flowDefinition = -1;
            model.flowdefinitions = operation.GetList<FlowDefinition>();
            return View(model);
        }
        [HttpPost]
        public ActionResult Add(flowdefmodellist model)
        {
            ViewBag.message = model.id_flowDefinition;
            flowdef.id_flowDefinition = model.id_flowDefinition;
            flow.id_flowdefinition = flowdef;
            flow.id_position = operation.GetPositionidFlow(model.id_flowDefinition);
            flow.id_user = user;
            flow.Name = model.name;
            if (flow.id_flowdefinition != null && flow.id_position != null && flow.id_user != null && flow.Name != null)
            {
                operation.AddElement<Flow>(flow);
            }
            
            return View();
        }

        



    }
}

WebApplication1/Views/PickFlow/Add.cshtml
@{
    ViewBag.Title = "Add";

}
@ViewBag.message;
<h2>Add</h2>

WebApplication1/Views/PickFlow/Index.cshtml
@model  WebApplication1.Models.flowdefmodellist
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @using (Html.BeginForm("Add", "PickFlow", FormMethod.Post))
    {
        <h2>Choose Flow</h2>
        <div class="dropdown">
            @Html.DropDownListFor(m => m.id_flowDefinition, new SelectList(Model.flowdefinitions, "id_flowDefinition", "Flow_name"), new { @class = "form-control" })
        </div>
        <br />
            @Html.TextBoxFor(m => m.name, new { @class = "form-control" })
        <br/>
            <input class="btn btn-primary" type="submit" value="submit" />
            }
        </div>