WebApplication1/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Xml;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Dynamic;
using WebApplication1.Models;
using WorkFlowDesigner;
using System.Xml.Serialization;

namespace WebApplication1.Controllers
{
    
    public class TasksController : Controller
    {
        // GET: Tasks
        
        private IList<Step> steplist = new List<Step>();
        
        public ActionResult Index()
        {
            User user = (User)Session["users"];
            if(user == null) return RedirectToAction("Index", "Login");

            NH.NHibernateOperation operation = new NH.NHibernateOperation();

            IList<Task> tasks = operation.GetUserTasks(user);
            List<int> numbers = new List<int>();

            foreach (Task t in tasks)
            {
                numbers.Add(t.Id_position.Id_position);
            }

            IList<Position> positions = operation.GetUserPositions(numbers);

            Dictionary<Position, IList<Flow>> map = new Dictionary<Position, IList<Flow>>();

            foreach (Position p in positions)
            {
                map.Add(p, operation.GetUserActiveFlows(p));
            }
            TaskModel task = new TaskModel();
            task.Map = map;
            ViewBag.Task = task;
            
            //List<string[]> list = parser.Condition(cond);
            

            return View();
            
        }
        
        public Item findItem(string name, Items items)
        {
            foreach(Item item in items.itemList)
            {
                if (item.id.name.Equals(name)) return item;
            }
            return null;
        }

        public ActionResult Execute(int number)
        {          
            
            string id = (string)RouteData.Values["id"];
            int position = Int32.Parse(id);
            User user = (User)Session["users"];
            if (user == null) return RedirectToAction("Index", "Login");
            NH.NHibernateOperation operation = new NH.NHibernateOperation();

            List<int> users = operation.GetUsersByPosition(position);
            if (!users.Contains(user.Id_user)) ViewBag.Result = 403;

            Position p = operation.FindPositionById(position);
            IList<Flow> flows = operation.GetUserActiveFlows(p);
            Flow flow = new Flow();
            foreach (Flow f in flows)
            {
                if (f.id_flow == number)
                {
                    ViewBag.Flow = f;
                    flow = f;
                    break;
                }
            }
            FlowDefinition fl = operation.GetFlowDefinition(flow.id_flowdefinition.id_flowDefinition);
            Document doc = operation.GetDocumentByName(fl.Flow_name);
            byte[] data = doc.Data;
            string str2 = System.Text.Encoding.UTF8.GetString(data, 0, data.Length);
            string sub = str2.Substring(1);

            XmlSerializer deserializer = new XmlSerializer(typeof(Items));
            XmlDocument docxml = new XmlDocument();
            docxml.LoadXml(sub);
            XmlNodeReader node = new XmlNodeReader(docxml);
            object obj = deserializer.Deserialize(node);
            Items XmlData = (Items)obj;
            node.Close();
            Dictionary<string, Item> itemMap = new Dictionary<string, Item>();
            foreach(Item it in XmlData.itemList)
            {
                if(it.id.name.Equals("Item "))
                {
                    it.id.name = "check";
                }
                itemMap.Add(it.id.name, it);
            }

            IList<Attributes> attrList = operation.GetAttributesByFlow(flow.id_flowdefinition.id_flowDefinition);
            FullFlowModel model = new FullFlowModel();
            model.list = new List<FlowModel<string>>();
            model.list_int = new List<FlowModel<int>>();
            model.values = new List<string>();
            model.items = XmlData;
            foreach (Attributes a in attrList)
            {

                Access acc = operation.GetAttributeAccess(position, a.Id_attribute);
                if(acc.Read_property==1 && (acc.Required_change==1 || acc.Optional_change == 1))
                {
                    if (a.Type.Equals("int"))
                    {
                        FlowModel<int> f = new FlowModel<int>();
                        f.name = a.Name;
                        f.required = acc.Required_change;
                        f.type = a.Type;
                        f.item = itemMap[a.Name];
                        model.list_int.Add(f);
                    } 
                    else
                    {
                        FlowModel<string> f = new FlowModel<string>();
                        f.name = a.Name;
                        f.required = acc.Required_change;
                        f.type = a.Type;
                        f.item = itemMap[a.Name];
                        if (a.Type.Equals("list"))
                        {
                            IList<ListElement> ll = operation.GetAttributeList(a.Id_attribute);
                            List<string> str = new List<string>();
                            str.Add(null);
                            foreach(ListElement l in ll)
                            {
                                str.Add(l.Name);
                            }
                            f.list = str;
                        }
                        model.list.Add(f);
                    }
                    
                } else if(acc.Read_property ==1)
                {
                    FlowExtension ext = operation.FindExtension(flow.id_flow, a.Id_attribute);
                    if(ext!=null) model.values.Add(a.Id_attribute.ToString() + " = "+ext.Value);
                }
                
            }
            ViewBag.Test = model;

            int max = 0;
            foreach(Item i in XmlData.itemList)
            {
                if ((i.location.y + i.size.height) > max)
                {
                    max = (i.location.y + i.size.height);
                }
            }

            max = max + 70;
            ViewBag.Max = max.ToString()+"px";

            ViewBag.Tekst = "";

            return View(model);
        }

        public static string ConvertHexToString(String hexInput, System.Text.Encoding encoding)
        {
            int numberChars = hexInput.Length;
            byte[] bytes = new byte[numberChars / 2];
            for (int i = 0; i < numberChars; i += 2)
            {
                bytes[i / 2] = Convert.ToByte(hexInput.Substring(i, 2), 16);
            }
            return encoding.GetString(bytes);
        }

        [HttpPost]
        public ActionResult Change(FullFlowModel model)
        {
            User user = (User)Session["users"];
            if (user == null) return RedirectToAction("Index", "Login");

            NH.NHibernateOperation operation = new NH.NHibernateOperation();

            string id = (string)RouteData.Values["id"];
            int f= Int32.Parse(id);
            Flow flow = operation.FindFlowById(f);

            Position p = operation.FindPositionById(flow.id_position.Id_position);
            ViewBag.Pos = p.Id_position;
            Step step = operation.FindStep(p);         
            ViewBag.Model = model;

            if (step != null)
            {
                flow.id_position = step.End_position_id;

                String cond = step.Condition;
                if (cond != null)
                {
                    Parser parser = new Parser();
                    string[] list = parser.Parse(cond);
                    Dictionary<string, string> dict = new Dictionary<string, string>();

                    foreach (FlowModel<string> mdl in model.list)
                    {
                        dict.Add(mdl.name, mdl.value);
                    }
                    foreach (FlowModel<int> mdl in model.list_int)
                    {
                        dict.Add(mdl.name, mdl.value.ToString());
                    }

                    List<bool> bool_list = new List<bool>();
                    List<string> sign = new List<string>();
                    foreach (string s in list)
                    {
                        string temp = s;
                        char start = s[0];
                        char end = s[s.Length - 1];
                        string str = "";
                        string en = "";

                        if (start.Equals("|") || start.Equals("&"))
                        {
                            temp = s.Substring(2, s.Length - 2);
                            str = "" + start + start;
                            sign.Add(str);
                        }
                        if (end.Equals("|") || end.Equals("&"))
                        {
                            temp = temp.Substring(0, temp.Length - 2);
                            en = "" + end + end;
                            sign.Add(en);
                        }

                        bool result = parser.checkBracket(temp, dict);
                        bool_list.Add(result);
                    }

                    bool wynik = bool_list[0];
                    for (int i = 0; i < sign.Count; i++)
                    {
                        if (sign.Equals("||"))
                        {
                            wynik = wynik || bool_list[i + 1];
                        }
                        else
                        {
                            wynik = wynik && bool_list[i + 1];
                        }
                    }

                    if (wynik == true)
                    {
                        MailController mm = new MailController();
                        

WebApplication1/Views/Tasks/Change.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "Change";
}
<div class="container">
<h2>Change</h2>
<h2>@ViewBag.Pos</h2>

@{ 
    
    foreach(FlowModel<string> f in ViewBag.Model.list)
    {
        <h2>@f.name = @f.value</h2>        
        <h2>---------</h2>
    }
    foreach (FlowModel<int> f in ViewBag.Model.list_int)
    {
        <h2>@f.name = @f.value</h2>
        <h2>---------</h2>
    }
}
</div>

WebApplication1/Views/Tasks/Execute.cshtml
@model WebApplication1.FullFlowModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Execute";
}

<div class="container">
    @if (ViewBag.Result == 403)
    {
        <h1>403</h1>
        <h2>You don't have permissions</h2>
    }
    else
    {
        <h2>Edit Flow</h2>
        <h3>@ViewBag.Flow.Name</h3>


        <h4>@ViewBag.Tekst</h4>
        Html.RenderPartial("~/Views/Tasks/TaskForm.cshtml");
    }
</div>

WebApplication1/Views/Tasks/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "Index";
}


<h2>Your positions</h2>


@foreach (KeyValuePair<Position, IList<Flow>> item in ViewBag.Task.Map)
{
    <h2>@item.Key.Name</h2><br/>

    if (item.Value.Count == 0)
    {
        <h2>You don't have task to do in this position</h2>
    }
    

    for (int i = 0; i < item.Value.Count; i++)
    {
        <h3>@item.Value[i].Name</h3>
        <button type="button" onclick="location.href='@Url.Action("Execute", "Tasks", new { id = item.Key.Id_position, number = item.Value[i].id_flow })' ">Do it</button><br />
        <br/>
    }
}

WebApplication1/Views/Tasks/TaskForm.cshtml
@model WebApplication1.FullFlowModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using WebApplication1.Models;

<div style="position: relative; height:@ViewBag.Max;" class="container">

    @{
        int max_height = int.MinValue;
        using (Html.BeginForm("Change", "Tasks", new { @id = @ViewBag.Flow.id_flow }, FormMethod.Post, new { id = "test" }))
        {

            for (var i = 0; i < @Model.list.Count; i++)
            {

                Item item = new Item();
                string type = "text";
                item = Model.list[i].item;
                string y1 = "" + item.location.y + "px";
                string x1 = "" + item.location.x + "px";
                string h1 = "height:" + item.size.height + "px; width:"+item.size.width+"px;";
                
                if ((item.location.y + item.size.height) > max_height) { max_height = (item.location.y+item.size.height); }

                if (Model.list[i].type.Equals("checkbox"))
                {
                    type = "checkbox";
                    if (Model.list[i].required == 1)
                    {
                        <div  style="position: absolute;top:@y1;left:@x1;">
                            @Html.CheckBoxFor(m => m.list[i].Value_bool, new { required = "required" , @style = @h1 })
                            
                        </div>
                    }
                    else
                    {
                        <div  style="position: absolute;top:@y1;left:@x1;">
                            @Html.CheckBoxFor(m => m.list[i].Value_bool, new { @style = @h1 })
                            
                        </div>
                    }
                }
                else if (Model.list[i].type.Equals("list"))
                {
                    if (Model.list[i].required == 1)
                    {
                        <div class="dropdown" style="position: absolute;top:@y1;left:@x1;">
                            @Html.DropDownListFor(Model => Model.list[i].value, new SelectList(Model.list[i].list), new { @class = "form-control", required = "required", @style = @h1 })
                           
                        </div>
                    }
                    else
                    {
                        <div class="dropdown" style="position: absolute;top:@y1;left:@x1;">
                            @Html.DropDownListFor(Model => Model.list[i].value, new SelectList(Model.list[i].list), new { @class = "form-control",@style = @h1 })
                            
                        </div>
                    }
                }
                else
                {
                    if (Model.list[i].required == 1)
                    {
                        <div style="position: absolute;top:@y1;left:@x1;">
                            @Html.TextBoxFor(m => m.list[i].value, new { @class = "form-control",type = @type, required = "required", @style = @h1})
                            
                        </div>
                    }
                    else
                    {
                        <div style="position: absolute;top:@y1;left:@x1;">
                            @Html.TextBoxFor(m => m.list[i].value, new { @class = "form-control", type = @type, @style = @h1})
                            
                        </div>
                    }
                }

                @Html.TextBoxFor(m => m.list[i].name, new { @Value = @Model.list[i].name, @type = "hidden" })
            }

            for (var i = 0; i < @Model.list_int.Count; i++)
            {

                Item item = new Item();
                item = Model.list_int[i].item;
                //string pos = "position:absolute;bottom:" + item.location.y + "left:" + item.location.x;
                string y1 = "" + item.location.y + "px";
                string x1 = "" + item.location.x + "px";
                string h1 = "height:" + item.size.height + "px; width:" + item.size.width + "px;";

                if ((item.location.y + item.size.height) > max_height) { max_height = (item.location.y + item.size.height); }

                if (Model.list_int[i].required == 1)
                {
                    <div style="position: absolute;top:@y1;left:@x1;">
                        @Html.TextBoxFor(m => m.list_int[i].value, new { @class = "form-control", type = "number", required = "required",@style = @h1})
                        
                    </div>
                }
                else
                {
                    <div style="position: absolute;top:@y1;left:@x1;">
                        @Html.TextBoxFor(m => m.list_int[i].value, new { @class = "form-control", type = "number", @style = @h1})
                        
                    </div>
                }
                @Html.TextBoxFor(m => m.list_int[i].name, new { @Value = @Model.list_int[i].name, @type = "hidden" })
            }
            max_height = max_height + 10;
            string m2 = "" + max_height + "px";
            <div style="position: absolute;top:@m2"><input type="submit" value="Save" id="btnsave" name="btnsave" /></div>
            max_height = max_height + 30;
            m2 = "" + max_height + "px";
        }

    }
    @{string m3 = "" + max_height + "px";
    <div style="position: absolute;top:@m3">
        <h3>Pozostałe dane</h3>
        @foreach (String s in @Model.values)
        {
            <h4>@s</h4>
        }
    </div>
     }

</div>