WebApplication1/Controllers/AddDocumentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class AddDocumentController : Controller
    {
        public static User user;
        public static FlowDefinition flow;
        // GET: AddDocument
        public ActionResult Index()
        {
            if (user == null) return RedirectToAction("Index", "Login");
            return View();
        }

        
        [HttpPost]
        public ActionResult Add(HttpPostedFileBase uploadFile)
        {
           

            string flowvalue = Request["testSelect"];
            Document newDocument = new Document();
            NH.NHibernateOperation operation = new NH.NHibernateOperation();
            newDocument.Id_user = user;

            IList<FlowDefinition> flowlist = new List<FlowDefinition>();
            flowlist = operation.GetList<FlowDefinition>();
            foreach (FlowDefinition i in flowlist)
            {
                if (i.id_flow == Int32.Parse(flowvalue))
                {
                    newDocument.Id_flow = i;
                }
            }
           
                
            if (uploadFile != null)
            {
                string filePath = uploadFile.FileName;
                newDocument.Name = Path.GetFileName(uploadFile.FileName);
                string ext = Path.GetExtension(uploadFile.FileName);
                string contenttype = string.Empty;
                switch (ext)
                {
                    case ".doc":
                        contenttype = "application/vnd.ms-word";
                        break;
                    case ".docx":
                        contenttype = "application/vnd.ms-word";
                        break;
                    case ".pdf":
                        contenttype = "application/pdf";
                        break;
                }
                if (contenttype != String.Empty)
                {
                    byte[] bytes;
                    using (BinaryReader br = new BinaryReader(uploadFile.InputStream))
                    {
                        bytes = br.ReadBytes(uploadFile.ContentLength);
                    }
                    newDocument.Data = bytes;
                    newDocument.ContentType = contenttype;
                    operation.AddElement<Document>(newDocument);
                    return View("Index", "Account");
                }
            }
            return RedirectToAction("Index", "Account");
        }



    }







}

WebApplication1/Views/AddDocument/Index.cshtml
@{
    Layout = null;
}
<h2>Index2</h2>
@using (Html.BeginForm("Add", "AddDocument", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="uploadFile" />
    <input type="submit" />
    <select id="testSelect" name="testSelect"
            onclick="optclicked">
        @{ WebApplication1.NH.NHibernateOperation operation = new WebApplication1.NH.NHibernateOperation();
            FlowDefinition flow = new FlowDefinition();
            string FlowValue;
            IList<FlowDefinition> flowlist = new List<FlowDefinition>();
            flowlist = operation.GetList<FlowDefinition>();
            foreach (FlowDefinition i in flowlist)
            {
                <option value="@i.id_flow">@i.id_flow</option>
            }
            FlowValue = Request["testSelect"];
           
        }

    </select>
    

            }